### ISSUE TITLE
Linker Error when compiling for an iPhone5

### ISSUE THREAD

**Issue by narner** [pjebs/Obfuscator-iOS#14]
Hi there!

I'm currently trying to use Obfuscator-iOS in my app project. However, when building on the iPhone 5 simulator, I'm getting the following linker error:

<img width="842" alt="screen shot 2017-07-13 at 4 17 53 pm" src="https://user-images.githubusercontent.com/2131591/28186036-a9ed95ae-67e7-11e7-9bfb-7c5e4c6a78d3.png">

**Comment by pjebs** [comment]
Are you using cocoapods?

**Comment by narner** [comment]
I am indeed, yes!

**Comment by pjebs** [comment]
Try https://github.com/pjebs/Obfuscator-iOS/issues/2#issuecomment-256977913

**Comment by pjebs** [comment]
And adding manually and let me know

**Comment by narner** [comment]
Hey, adding in manually seemed to solve some of my problems - I think the `Obfuscator` problems I mentioned were solved, but I then got a lot of compile errors for the [RNCryptor](https://github.com/RNCryptor/RNCryptor) dependency I'm using as well...so, not entirely sure how to solve this.

**Comment by pjebs** [comment]
Maybe RNCryptor imports the same C libraries for crypto functions?
`#include <CommonCrypto/CommonCrypto.h>`

Should I close this issue?

**Comment by narner** [comment]
Yup, thats indeed the reason - thank you for helping me track this down!
