### ISSUE TITLE
For guidance, for help

### ISSUE THREAD

**Issue by flyOfYW** [pjebs/Obfuscator-iOS#16]
I found a problem with WeChat-related appkey, hexByObfuscatingString methods, such as "wxaa45ad08facad578", "wxaa45ad08uhtad578", I don't know if there is a way to solve it @pjebs

**Comment by pjebs** [comment]
can you provide more details

**Comment by flyOfYW** [comment]
Obfuscator *o = [Obfuscator newWithSalt:[YWVIewLisCtr class],[NSString class],nil];
    NSString *origParseKey = @"wxf1e5d5ee0f9ef510";
    [o hexByObfuscatingString:origParseKey];

2019-02-26 11:35:04.532 Example[5363:203129] Could not obfuscate: wxf1e5d5ee0f9ef510 - Use different salt
2019-02-26 11:35:04.532 Example[5363:203129] 

decoded: JEG3i8R9LAXIDW0kXGHGjauak0G2mAjPacv1QfkO
 ob:JEG3i8R9LAXIDW0kXGHGjauak0G2mAjPacv1QfkO

I found that rules like "wxaa45ad08uhtad578" have a high probability of error

**Comment by pjebs** [comment]
You need to add way more classes for security reasons. 2 is not enough.

**Comment by flyOfYW** [comment]
Ok, thank you
