### ISSUE TITLE
Errors: (1) Expected ';' after method prototype and (2) Expected identifier in Obfuscator.h 

### ISSUE THREAD

**Issue by askarimov** [pjebs/Obfuscator-iOS#3]
Getting errors:
(1) Expected ';' after method prototype
(2) Expected identifier 

at two method declarations in Obfuscator.h file
- (instancetype)newWithSalt:(Class)class, ... NS_REQUIRES_NIL_TERMINATION; 
  and 
- (void)storeKey:(NSString *)key forSalt:(Class)class, ... NS_REQUIRES_NIL_TERMINATION;

Renaming `class` to some other name fixed the errors.

**Comment by pjebs** [comment]
Are you installing using cocoapods to install the library? I assume you aren't because you changed the code yourself.
Can you send me a small sample project that showcases the issue?

I don't get the issue at all. I'm using Xcode 7.1 but I developed this library when I was using Xcode 6.

**Comment by askarimov** [comment]
I am installing using cocoapods and i am able to unlock the code to change it.

The project where I am trying to obfuscate strings was created using XCode 5 or 6. If I create a new project with XCode 7, the code compiles without any errors. The issue might be in some build settings differences. Therefore can't send you a sample. Cant find the solution.

Any suggestions?
