### ISSUE TITLE
hexByObfuscatingString fails due to XOR anomaly

### ISSUE THREAD

**Issue by mfcollins3** [pjebs/Obfuscator-iOS#6]
I added Obfuscator-iOS to my project via CocoaPods and followed the directions to obfuscate strings. I'm trying to use hexByObfuscatingString: to obfuscate a secret key for GitHub's API, but I keep getting an error that it could not obfuscate my secret key string.

I walked through the code and I think that the problem is at line number 164 in Obfuscator.m. In the reveal: method, there's this line of code:

```
*dataPtr = *dataPtr ^ *keyPtr;
```

The problem that I am seeing is that both `*dataPtr` and `*keyPtr` point to the character '8' at one index. Therefore, '8' XOR '8' is going to be byte 0. Because the code is operating on C strings, this '0' byte is prematurely terminating the obfuscated string and the obfuscated version appears to be truncated.

**Comment by pjebs** [comment]
Hi Michael,

It's not actually a bug in the code. In fact, it's the key to how the obfuscator works!
What you are seeing is a limitation of the technique. The only way around it is to change your salt (i.e. add more classes) and try again: 

See https://github.com/pjebs/Obfuscator-iOS/blob/master/README.md#L125

If you instead use the technique listed under "More Advanced Usage", you will notice that `generateCodeWithSalt` method will automate the process of obfuscating all your strings. **This is the preferred method to use**

**Comment by mfcollins3** [comment]
Thanks for responding. Yes, I realized as I was looking at the code more that there is really no way around this given how the code is currently implemented because it uses reveal: for both obfuscation and reversal.

If you ever re-write that part, it might be a good idea to use different methods for obfuscating and reversing. Instead of modifying the C-string in-place, you could use an NSMutableString to build the obfuscated string and implement some kind of marker for a zero byte.

**Comment by pjebs** [comment]
I think you are right. For the Next version I will do that
