### ISSUE TITLE
Not all classes are acceptable as salt

### ISSUE THREAD

**Issue by msalman** [pjebs/Obfuscator-iOS#7]
Hi,

While creating a Obfuscator object I came across an issue where not all my classes are obfuscating the key successfully. For example if I use any of the below set of classes as a salt I always get error **Could not obfuscate - Use different salt**

```
Obfuscator *o = [Obfuscator newWithSalt:[NSString class], [NSObject class], [NSString class], nil];
or
//Application is a class define in my project
Obfuscator *o = [Obfuscator newWithSalt:[Application class], [NSString class], nil];
or 
//Rename class from Application to Applicatio
Obfuscator *o = [Obfuscator newWithSalt:[Applicatio class], [NSString class], nil];
or
//Rename class from Application to Applicatin
Obfuscator *o = [Obfuscator newWithSalt: [Applicatin class], [NSObject class], nil];
or
//Protection is a class in my application
Obfuscator *o = [Obfuscator newWithSalt: [Protection class], [NSString class], nil];
or
//Protection is a class in my application
Obfuscator *o = [Obfuscator newWithSalt: [Protection class], [NSObject class], nil];
```

Whereas below set of classes are acceptable

```
// Using NSString and NSObject as salt
Obfuscator *o = [Obfuscator newWithSalt:[NSString class], [NSObject class], nil];
or
Obfuscator *o = [Obfuscator newWithSalt:[NSString class], [NSString class], [NSString class], nil];
or
//Rename class from Application to Applicatin
Obfuscator *o = [Obfuscator newWithSalt:[Applicatin class], [NSString class], nil];
```

I am not sure if any of the character in class name is causing this issue. If there is any limitation in using the specific characters in class name for salt than let me know.

**Comment by pjebs** [comment]
I think you are misunderstanding of how it works.
The `newWithSalt` method just converts the classes into a `NSString` by applying the `SHA1` hashing algorithm. The salt(s) used by you does not necessarily determine if the obfuscator will work or not, hence your title for this issue is actually wrong.

Whether the salt _can be used_ is a **function of the salt** (which is for all intents and purposes a random `string` after hashing) and the _**set of strings**_ you are _trying_ to obfuscate.

Your title suggests that some classes **can not** be used ever as a valid salt. That is incorrect.

**Comment by pjebs** [comment]
In your examples: Find out if your class(s) `Protection`... returns a proper string for the `class` method.
If it does not in your examples they are all returns an empty string, so then it means by coincidence the `NSObject` and `NSString` class in your examples are not obfuscating your current set of strings.

Let me know.

**Comment by pjebs** [comment]
Finally add more classes. The more classes you add, the more likely it will successfully obfuscate **all** your strings

**Comment by pjebs** [comment]
Use `generateCodeWithSalt` instead because it does everything for you without forcing you to know how it works behind the scenes. Instructions are in the "more advanced usage" section.

**Comment by msalman** [comment]
The error message **Use Different salt** was suggesting that there is something wrong in my salt so I assume that something is wrong with class name which prevent my secret key from obfuscating.

After following your instruction on adding more classes and after trying different combinations of classes being used in salt, now I have been able to get a salt which successfully obfuscate my secret key.

Thanks for your prompt response.
