### ISSUE TITLE
Could not obfuscate Use different salt

### ISSUE THREAD

**Issue by dholdaway** [pjebs/Obfuscator-iOS#8]
when trying to obfuscate a web address with a hyphen in it, it returns  

2016-06-15 13:27:36.955 Impl.[47263:1595477] Could not obfuscate: http://xxx-xx.xxxxxxxx.xxx/ - Use different salt

any ideas how i can get around this ? 

works fine with all my other variables which dont have special characters.

**Comment by pjebs** [comment]
Yes. Just add more classes to `generateCodeWithSalt:`

```
[Obfuscator generateCodeWithSalt:@[[NSString class], [AppDelegate class], [NSObject class]]
                         WithStrings:@[
                                       @{@"id": @"webAddress", @"string":@"http://xxx-xx.xxxxxxxx.xxx/"},
                                       @{@"id": @"BB", @"string":@"testKey"},
                                       @{@"id": @"CC", @"string":@"parseKey1234"},
                                       ]];
```

**Comment by pjebs** [comment]
Add as many classes as you want and for each class added, you increase the chance of obfuscating significantly. Special characters are not the issue.

**Comment by dholdaway** [comment]
yep that did the trick, i miss read the documentation.
